version: '3.0'

services:
  postgres_db:
      image: "postgres_db:db-rest"
      container_name: "postgres_db"
      build: ./database/
      ports:
        - "${DB_PORT}:${DB_PORT}"
      volumes:
        - database:/var/lib/postgresql/data
      networks:
        - my-net
      environment:
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_DB=${POSTGRES_DB}

  fastify-api:
      image: "unique-http:rest-api" 
      container_name: unique-http 
      build: .
      ports:
         - "${PORT}:${PORT}" 
      environment: 
        - PORT=${PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      networks:
        - my-net
      volumes:
        - logs:/app/logs
        - ./src:/app/src
      restart: on-failure
      depends_on:
       - postgres_db
      


networks:
   my-net:
      driver: bridge
volumes:
    logs:
    database: