version: '3.0'

services:
  fastify-api:
      image: "unique-http:rest-api" 
      container_name: unique-http 
      build: .
      ports:
         - "${PORT}:${PORT}" 
      environment: 
        PORT: "${PORT}"
      networks:
        - my-net
      volumes:
        - ./logs:/app/logs/
      restart: on-failure
      depends_on:
       - postgresql
      




  postgresql:
      image: "postgres-db:db-rest"
      container_name: "postgres-db"
      build: ./database/
      ports:
        - "${DB_PORT}:${DB_PORT}" 
      volumes:
        - ./database:/var/lib/postgresql/data
      networks:
        - my-net
      environment:
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_DATA: ${DB_USER}
        DB_ADD: ${DB_ADD}

networks:
   my-net:
      driver: bridge
volumes:
    logs:
    database: